### ISSUE TITLE
网络错误，浏览器正常访问

### ISSUE THREAD

**Issue by dawnluxin** [LiuLang/bcloud#104]
2015-01-02 16:06:57,906 ERROR 鍥剧墖.on_load: None, Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 81, in do_call
    result = func(*args)
  File "/usr/lib/python3/dist-packages/bcloud/pcs.py", line 666, in get_category
    req = net.urlopen(url, headers={'Cookie': cookie.header_output()})
  File "/usr/lib/python3/dist-packages/bcloud/net.py", line 86, in urlopen
    req = opener.open(url, data=data, timeout=timeout)
  File "/usr/lib/python3.2/urllib/request.py", line 370, in open
    response = self._open(req, data)
  File "/usr/lib/python3.2/urllib/request.py", line 388, in _open
    '_open', req)
  File "/usr/lib/python3.2/urllib/request.py", line 348, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 1160, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.2/urllib/request.py", line 1145, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.2/http/client.py", line 1052, in getresponse
    response.begin()
  File "/usr/lib/python3.2/http/client.py", line 346, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.2/http/client.py", line 308, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.2/socket.py", line 287, in readinto
    return self._sock.recv_into(b)
socket.error: [Errno 104] Connection reset by peer

**Comment by jtliaw** [comment]
不要记录密码，和不自动登陆试试看！

**Comment by LiuLang** [comment]
是一直出现这样的错误而导致无法使用吗? 还是偶尔出现一次?

**Comment by dawnluxin** [comment]
那天下午一直登录不上，晚上就好了！但是我的网络一直是通的！记住密码和自动登录的多选框是无法操作的！

**Comment by dawnluxin** [comment]
现在已经好了，谢谢所有开发人员以及贡献者！！
