### ISSUE TITLE
下载文件State Error

### ISSUE THREAD

**Issue by updogliu** [LiuLang/bcloud#126]
一个3G的电影，下载4,5M后State由Downloading变成Error。点Start后能继续下载4,5M，然后又变为Error。一直是这样。
![bcloud_download_error](https://cloud.githubusercontent.com/assets/1288299/6202266/db945fc0-b493-11e4-9f28-1ec87f915b48.png)

**Comment by SmilingSun** [comment]
Ubuntu 14.04 64bit，昨晚开始，有些文件也是这样，Error之后能接着下载一会儿，又变为Error。

```
2015-02-23 09:20:05,781 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 71, in get_req
    return opener.open(self.url, timeout=self.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 493, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 676, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)                                                                                                                                        
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by LiuLang** [comment]
这个可能是百度服务器禁止了之后的数据下载请求.
我测试了下, 同样的文件, 并没有出现问题.
我会关注这类错误的.
![screenshot from 2015-03-02 20 54 36](https://cloud.githubusercontent.com/assets/4401290/6441309/96f09916-c121-11e4-987f-feac0f4074c9.png)

**Comment by updogliu** [comment]
能否先加个对这种error隔几十秒自动resume?

On Mon, Mar 2, 2015 at 5:21 AM, LiuLang <notifications@github.com> wrote:

> 这个可能是百度服务器禁止了之后的数据下载请求.
> 我测试了下, 同样的文件, 并没有出现问题.
> 我会关注这类错误的.
> [image: screenshot from 2015-03-02 20 54 36]
> <https://cloud.githubusercontent.com/assets/4401290/6441309/96f09916-c121-11e4-987f-feac0f4074c9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiuLang/bcloud/issues/126#issuecomment-76710137>.
>



-- 
Regards,
Zihan, Sheldon Liu
------------------------------------------------
Software Engineer @ Google Inc.

**Comment by SmilingSun** [comment]
是的，过了一段时间，这个文件又能接着下载了。
是不是百度云对API接入有访问频率或者下载次数、流量的限制？

**Comment by LiuLang** [comment]
@updogliu 
这个是可以在"首选项"中设置的. 可以将它设定为1分钟, 即下载出错1分钟以后会自动重启这个任务.

@SmilingSun 
下载出错, 多半是因为与百度服务器建立的连接中断了, 需要重新连它. 而且, 为了防止被服务器标记为恶意请求(短时间内出现大量的下载尝试), 就把重试下载的操作推迟了一些时间.
