### ISSUE TITLE
ArchLinux KDE和Gnome下报错无 _Py_ZeroStruct

### ISSUE THREAD

**Issue by lineves** [LiuLang/bcloud#131]
$ bcloud-gui
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.4/site-packages/bcloud/App.py", line 22, in <module>
    from bcloud import gutil
  File "/usr/lib/python3.4/site-packages/bcloud/gutil.py", line 13, in <module>
    import dbus
  File "/usr/lib/python2.7/site-packages/dbus/__init__.py", line 82, in <module>
    import dbus.types as types
  File "/usr/lib/python2.7/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: /usr/lib/python2.7/site-packages/_dbus_bindings.so: undefined symbol: _Py_ZeroStruct

**Comment by libertas** [comment]
正确安装了吗？
我的环境和你一样，但是没有问题。
你重新安装一下，然后把安装的输出贴出来看看可以吗？

**Comment by lineves** [comment]
ackages (1) bcloud-git-20150306-1

Total Installed Size:  0.75 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                     [##########################################################################################] 100%
(1/1) checking package integrity                                                                                                                   [##########################################################################################] 100%
(1/1) loading package files                                                                                                                        [##########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                  [##########################################################################################] 100%
(1/1) checking available disk space                                                                                                                [##########################################################################################] 100%
(1/1) installing bcloud-git                                                                                                                        [##########################################################################################] 100%

==> Checking vote status for bcloud-git
^C
[onetwo@onetwo 1]$ bcloud-gui
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.4/site-packages/bcloud/App.py", line 22, in <module>
    from bcloud import gutil
  File "/usr/lib/python3.4/site-packages/bcloud/gutil.py", line 13, in <module>
    import dbus
  File "/usr/lib/python2.7/site-packages/dbus/__init__.py", line 82, in <module>
    import dbus.types as types
  File "/usr/lib/python2.7/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: /usr/lib/python2.7/site-packages/_dbus_bindings.so: undefined symbol: _Py_ZeroStruct



已经换成 KDE 尝试依然如故

**Comment by libertas** [comment]
看起来是python-dbus的问题？
我猜你可以试试删除+重装python-dbus和python2-dbus和python-dbus-common～

**Comment by lineves** [comment]
不过我这系统是新装的，按理说是没问题的。
依赖有点多，我周末再试试吧，谢谢你的建议～

**Comment by Firef0x** [comment]
@lineves ，您好！

这个问题有点蹊跷，我仅提供另一个思路，见：

[百度云管家Linux桌面客户端BCloud已经进入Community仓库 - 6楼](https://bbs.archlinuxcn.org/viewtopic.php?pid=20325#p20325)
[百度云管家Linux桌面客户端BCloud已经进入Community仓库 - 8楼](https://bbs.archlinuxcn.org/viewtopic.php?pid=20331#p20331)
[Python2试图import pygtk时出现错误](https://bbs.archlinuxcn.org/viewtopic.php?id=2900)

此致！ :bow:

**Comment by LiuLang** [comment]
@lineves 
怎么样? 问题解决了么?
有位ubuntu用户也遇到了类似的问题.
正常情况下, bcloud是要载入python3版的dbus模块的, 但在你这里, 却载入了python2版本的了, 就会出现错误!

**Comment by lineves** [comment]
问题已定位…

我把宿舍自己用的电脑，用自己的用户环境当生产环境，为了运行一系列服务在 /etc/profile 的最后添加了 export PYTHONPATH=/usr/lib/python2.7/site-packages/

所以默认搜索2.7的包。

尝试修改为 export PYTHONPATH=/usr/lib/python2.7/site-packages/:/usr/lib/python3.4/site-packages/   无效，
尝试修改为 export PYTHONPATH=/usr/lib/python3.4/site-packages/:/usr/lib/python2.7/site-packages/   有效，问题解决。



所以直接原因是 PYTHONPATH 设置为了2.7 ，根本原因是在生产环境上玩耍，解决方案是  Arch 用户在 /etc/profile 的最后添加 export PYTHONPATH=/usr/lib/python3.4/site-packages/
ubuntu用户请类推。

感谢大神们的耐心和启发！！！

**Comment by LiuLang** [comment]
嗯, 问题解决了就好
