### ISSUE TITLE
瘋狂的錯誤+自動關閉

### ISSUE THREAD

**Issue by laichiaheng** [LiuLang/bcloud#150]
目前使用elementary OS ( 基於Ubuntu14.04 ) 的版本，/.config/bcloud/bcloud.log錯誤訊息如下
由於紀錄檔太長，我只有擷取上半部一點點

2015-04-15 00:02:25,842 ERROR DownloadBatch, block is empty: 92703838, 77799449, 155598897, b''
2015-04-15 00:02:49,378 ERROR DownloadBatch, block is empty: 249504931, 249071788, 373607682, b''
2015-04-15 00:02:57,310 ERROR DownloadBatch, block is empty: 83865597, 76301230, 114451847, b''
2015-04-15 00:03:27,515 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

2015-04-15 00:04:23,774 ERROR DownloadBatch, block is empty: 39058572, 33447973, 66895945, b''
2015-04-15 00:05:31,178 ERROR DownloadBatch, block is empty: 71248598, 48729732, 73094600, b''
2015-04-15 00:07:39,472 ERROR DownloadBatch, block is empty: 80159520, 68654773, 137309545, b''
2015-04-15 00:19:47,729 ERROR DownloadBatch, block is empty: 167308422, 155598898, 233398349, b''
2015-04-15 16:46:09,490 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

2015-04-15 16:48:50,628 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

2015-04-15 17:01:21,098 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

2015-04-15 17:07:26,472 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

2015-04-15 17:35:14,337 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 90, in download
    block = req.read(CHUNK_SIZE)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by laichiaheng** [comment]
![2015-05-12 15 54 13](https://cloud.githubusercontent.com/assets/9532105/7582353/2f8f3d2e-f8bf-11e4-80b2-f32dda74f89d.png)
這是我剛剛下載的圖片
順代一提，如果有出現過錯誤，重新下載後的檔案通常都會有點問題
譬如我的flac檔要用soundkonverter計算replaygain時(平衡每首歌曲間音量的)會無法計算

**Comment by imzf** [comment]
我这里也经常下载出错。有时会自动崩溃

**Comment by LiuLang** [comment]
On 05/12/2015 03:56 PM, laichiaheng wrote:
> ![2015-05-12 15 54 13](https://cloud.githubusercontent.com/assets/9532105/7582353/2f8f3d2e-f8bf-11e4-80b2-f32dda74f89d.png)
> 這是我剛剛下載的圖片
> 順代一提，如果有出現過錯誤，重新下載後的檔案通常都會有點問題
> 譬如我的flac檔要用soundkonverter計算replaygain時(平衡每首歌曲間音量的)會無法計算
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/150#issuecomment-101177345
>

我会确认一下这个问题的.

**Comment by laichiaheng** [comment]
其實我覺得最要解決的是自動關閉的問題
因為下載失敗感覺是因為百度他們自己的問題
百度說真的很爛，其他空間就不會有他這種狀況
要不是他空間大，要不然根本不會有什麼人用吧

**Comment by pingplug** [comment]
我还以为只是IPv6的问题。。。 #97 
以及有些时候重新打开bcloud任务会double。。。
![2015-05-22 09-32-29](https://cloud.githubusercontent.com/assets/6712475/7762350/e78dbc68-0065-11e5-8153-f76e3c93383f.png)

**Comment by HybridGlucose** [comment]
@laichiaheng 不過windows端的程式好像沒有這問題
是因為百度自己會自動重試？

**Comment by laichiaheng** [comment]
最新版本還是一樣會狂閃退，不知道這紀錄有沒有被記在log裡面...

**Comment by baoyankun** [comment]
晕，出现过ERROR的任务文件会有问题？我已经用bcloud下了接近2TB的东西，很多都没检查过...

**Comment by laichiaheng** [comment]
@baoyankun 我是音樂和影片檔會有問題，壓縮檔看運氣
