### ISSUE TITLE
無法刪除表單中錯誤的下載項目

### ISSUE THREAD

**Issue by laichiaheng** [LiuLang/bcloud#151]
系統：elementary OS ( based on Ubuntu 14.04 ) 
![2015-05-17 13 13 31](https://cloud.githubusercontent.com/assets/9532105/7669184/91b8418c-fc96-11e4-9e73-c568bf10d0a3.png)
按 "—" 字號無法刪除項目

**Comment by LiuLang** [comment]
On 05/17/2015 01:15 PM, laichiaheng wrote:
> 系統：elementary OS ( based on Ubuntu 14.04 )
> ![2015-05-17 13 13 31](https://cloud.githubusercontent.com/assets/9532105/7669184/91b8418c-fc96-11e4-9e73-c568bf10d0a3.png)
> 按 "—" 字號無法刪除項目
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/151
>

这是一个bug, 正在修复. 谢谢你的反馈

**Comment by laichiaheng** [comment]
請問這是要再下次更新才會有嗎？

**Comment by imzf** [comment]
@laichiaheng 已经修复了，你可以下载最新的代码手动安装。或者下载我用官方项目中的脚本生成的软件包http://pan.baidu.com/s/1bnDBKEr

**Comment by laichiaheng** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    external_cssselect = __import__('cssselect')
ImportError: No module named 'cssselect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3/dist-packages/bcloud/App.py", line 23, in <module>
    from bcloud import gutil
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/usr/lib/python3/dist-packages/bcloud/pcs.py", line 15, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 18, in <module>
    raise ImportError('cssselect seems not to be installed. '
ImportError: cssselect seems not to be installed. See http://packages.python.org/cssselect/
這是我用您給我的那個安裝的

**Comment by imzf** [comment]
@laichiaheng 
sudo apt-get install python3-pip  python3-setuptools python3-pyinotify
sudo pip3 install cssselect

**Comment by laichiaheng** [comment]
@imzf 請問一下，以官網上的deb檔來說，這幾個是不是都一定需要裝？我之前都沒有裝
另外請教一下，我之前有裝過個叫作python-pip的，會不會和python3-pip相衝阿？

**Comment by imzf** [comment]
运行成功了吗
1.请阅读https://github.com/LiuLang/bcloud-packages的帮助文件
2，不会，python-pip貌似是python2的软件包管理器，python3-pip是python3的软件包管理器

**Comment by laichiaheng** [comment]
@imzf 成功了，那麼我下pip指令用到的是哪個的呢？

**Comment by imzf** [comment]
@laichiaheng  pip3 install 是python3的
pip install 是python2的

**Comment by imzf** [comment]
@laichiaheng https://github.com/LiuLang/bcloud-packages

**Comment by i2000s** [comment]
请问这个功能哪个版本加入？我在使用3.8.2，好像还是不能删除下载任务。谢谢！

Update: 抱歉，刚从是我没有找到删除的按钮。确认可以删除。
