### ISSUE TITLE
下载速度始终是0K

### ISSUE THREAD

**Issue by mryux** [LiuLang/bcloud#157]
不知道从什么时候开始的,不管什么文件都下载不了,速度都是0kB/s。
我的环境是所有package都更新到最新的archlinux+xfce4。
有没有什么log可以check的？

**Comment by LiuLang** [comment]
On 06/22/2015 08:08 PM, Yu Xiang wrote:
> 不知道从什么时候开始的,不管什么文件都下载不了,速度都是0kB/s。
> 我的环境是所有package都更新到最新的archlinux+xfce4。
> 有没有什么log可以check的？
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/157
>

请检查一下~/.config/bcloud/里面的两个日志文件.

**Comment by memoz** [comment]
遇到同样的问题，bcloud-stderr.log显示：
```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 316, in run
    self.download()
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 166, in download
    if not os.path.exists(row[SAVEDIR_COL]):
  File "/usr/lib/python3.4/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-18: ordinal not in range(128)
```
把系统语言改为en_US.UTF-8就好了。

**Comment by mhohai** [comment]
默认系统语言是en的路过。。。
