### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by xlfjn** [LiuLang/bcloud#158]
我现在使用的bcloud版本是3.7.1，Arch Linux源提供。（3.7.1-2）
下载各种较小的文件是没有任何问题的，但我试着下一个1.3GB的文件，却发现开始后下载一点便显示“错误”了。
看了看~/.config/bcloud/bcloud.log，发现了如下的内容：
```
ERROR Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/bcloud/Downloader.py", line 77, in get_req
    return opener.open(self.url, timeout=self.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 501, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 684, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
于是我打开了Wireshark，部分请求能够成功响应，而那些被403的返回JSON如下：
```json
{
    "error_code":31326,
    "error_msg":"anti hotlinking"
}
```
不知是否我个人的问题

**Comment by imzf** [comment]
也有这个问题，必须重试n次，才有一次成功的

**Comment by mryux** [comment]
看来不是只有我遇到这个问题，同样的403错误，同样是archlinux。

**Comment by laichiaheng** [comment]
百度他們不知道在搞什麼，下載到現在還是很容易失敗
至於bcloud是在我刪除任務後，容易過一段時間自己關閉

**Comment by pingplug** [comment]
段错误的问题早就有了，只要不频繁开始暂停就好

**Comment by LiuLang** [comment]
这个错误我之前也没仔细看, 好像是百度服务器端做了过滤, 我会抽空再研究一下它自己的客户端, 找出来发送的数据包的差异究竟在哪里, 这样就可以模仿官方的客户端请求数据了.

**Comment by xlfjn** [comment]
昨晚又试了试，能下载了（只是速度较慢且起伏剧烈），估计那个错误是百度服务器一时抽风罢。
（另：为何把User Agent设为这个：Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.2.0 ？）

**Comment by LiuLang** [comment]
On 07/02/2015 12:56 PM, xlfjn wrote:
> 昨晚又试了试，能下载了（只是速度较慢且起伏剧烈），估计那个错误是百度服务器一时抽风罢。
> （另：为何把User Agent设为这个：Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.2.0 ？）
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/158#issuecomment-117906137
>

这个没什么, 是Iceweasel浏览器用到上的.

**Comment by maz-1** [comment]
同样有这个问题，基本上几百m以上的文件都会出错

**Comment by LiuLang** [comment]
好的, 我会检查一下这个问题的

**Comment by sickHamm** [comment]
@LiuLang 
百度云重定向到真正的下载链接时可能会检查User-agent，模拟云管家User-agent可能可以解决403问题。更新的PC_USER_AGENT本人测试下载速度更快。
个人少量文件测试成功，部分需重试。
#218 应该也是403问题
patch：

```
diff --git a/bcloud/const.py b/bcloud/const.py
index 85c2761..1e05989 100644
--- a/bcloud/const.py
+++ b/bcloud/const.py
@@ -33,7 +33,7 @@ PCS_URL_D = 'http://d.pcs.baidu.com/rest/2.0/pcs/'

 ## 以下常量是模拟的PC客户端的参数.
 CHANNEL_URL = 'https://channel.api.duapp.com/rest/2.0/channel/channel?'
-PC_USER_AGENT = 'netdisk;4.5.0.7;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia'
+PC_USER_AGENT = 'netdisk;5.3.6.0;PC;PC-Windows;6.1.7601;WindowsBaiduYunGuanJia'
 PC_DEVICE_ID = '08002788772E'
 PC_DEVICE_NAME = '08002788772E'
 PC_DEVICE_TYPE = '2'
diff --git a/bcloud/pcs.py b/bcloud/pcs.py
index bbe41f3..6b77238 100644
--- a/bcloud/pcs.py
+++ b/bcloud/pcs.py
@@ -719,6 +719,7 @@ def get_download_link(cookie, tokens, path):
     req = net.urlopen_without_redirect(url, headers={
         'Cookie': cookie.sub_output('BAIDUID', 'BDUSS', 'cflag'),
         'Accept': const.ACCEPT_HTML,
+        'User-agent': const.PC_USER_AGENT,
     })
     if not req:
         return url
@@ -909,6 +910,7 @@ def get_metas(cookie, tokens, filelist, dlink=True):
     req = net.urlopen(url, headers={
         'Cookie': cookie.sub_output('BDUSS'),
         'Content-type': const.CONTENT_FORM,
+        'User-agent': const.PC_USER_AGENT,
         }, data=data.encode())
     if req:
         content = req.data
```

**Comment by KHN190** [comment]
@sickHamm 还是有403 Forbidden，但 https://github.com/acgotaku/BaiduExporter 就能用。
Bcloud的报头太长，BaiduExporter只有一个UserAgent参数。模拟的也是云管家。不知道还有哪里不对？

命令如：
`aria2c -c -s10 -k1M -x10 -o filename --header "User-Agent: netdisk;5.3.4.5;PC;PC-Windows;5.1.2600;WindowsBaiduYunGuanJia"  --header "Referer: http://pan.baidu.com/disk/home"  --header "Cookie: BDUSS=xxxxx;BAIDUID=xxxxx:FG=1"  "http://d.pcs.baidu.com/file/xxxhashxxx?params"`
