### ISSUE TITLE
ERROR SigninDialog.on_post_login: (18, None), None

### ISSUE THREAD

**Issue by drunkard** [LiuLang/bcloud#169]
最近两天登录不上了，错误日志如下：

2015-07-31 20:54:54,910 ERROR SigninDialog.on_post_login: (18, None), None
2015-07-31 20:56:10,126 ERROR SigninDialog.on_post_login: (18, None), None

另外，这种错误代码与原因的文档在哪里能找到呢？多谢

**Comment by sunzcdev** [comment]
我的也是，登录框下面出个未知错误，请重试。
是不是百度把api关闭了

**Comment by pingplug** [comment]
一样的问题， Arch 64位，bcloud为git版

**Comment by Arthurwu24** [comment]
同样的问题。。

**Comment by qband** [comment]
我也是arch 64，也是报这个错

**Comment by pingplug** [comment]
怀疑与 arch 最近更新的 python 组件有关
我不懂 python，有没有人测试一下？

**Comment by bianle** [comment]
我是ubuntu用户，bcloud可以登录，但是下载时报错
>ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by baoyankun** [comment]
今天早上开始登录不了了，和楼主一样。
2015-08-04 10:31:16,647 ERROR SigninDialog.on_post_login: (4, None), None
2015-08-04 10:31:19,256 ERROR SigninDialog.on_post_login: (4, None), None
2015-08-04 10:32:04,304 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-04 10:32:06,435 ERROR SigninDialog.on_post_login: (18, None), None

**Comment by DeviantTS** [comment]
ubuntu同样无法登陆
2015-08-05 11:21:09,346 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:21:23,737 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:21:27,447 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:27,686 ERROR SigninDialog.on_post_login: (4, None), None
2015-08-05 11:22:40,299 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:42,608 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:44,991 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:47,203 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:49,253 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:50,692 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-05 11:22:53,310 ERROR SigninDialog.on_post_login: (18, None), None

**Comment by hepha** [comment]
arch linux 64bit
2015-08-05 14:01:57,027 ERROR SigninDialog.on_post_login: (18, None), None

**Comment by A001tv** [comment]
Ubuntu14.04 64bit LTS 无法登录
Linuxmint 17.2 无法登录
2015-08-06 11:16:31,208 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 11:21:48,786 ERROR SigninDialog.on_post_login: (4, None), None
2015-08-06 11:22:18,469 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 11:27:55,447 ERROR SigninDialog.on_post_login: (18, None), None

**Comment by jtliaw** [comment]
我这里能登陆，也能下载！我的是bcloud 3.7.1

**Comment by wxyin** [comment]
Same here:(
![screenshot from 2015-08-07 18-41-18](https://cloud.githubusercontent.com/assets/13196353/9134180/71c1bffa-3d34-11e5-927f-ff81a5c3291b.png)

"Unknown error, please try again"

bcloud.log

2015-08-07 12:05:38,304 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 12:05:42,148 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 12:05:43,871 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 12:05:46,527 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 12:05:48,121 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 17:51:22,271 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:09:54,226 DEBUG Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2158, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/App.py", line 41, in <module>
    from gi.repository import AppIndicator3 as AppIndicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 144, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name AppIndicator3, introspection typelib not found

2015-08-07 18:10:03,152 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:17:24,948 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:18:18,266 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:21:01,906 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:27:11,828 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:27:28,918 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-07 18:29:25,688 ERROR SigninDialog.on_post_login: (18, None), None


Debian Stretch 

Package Info:
sudo aptitude show bcloud 
Package: bcloud                          
New: yes
State: installed
Automatically installed: no
Version: 3.7.2-1
Priority: optional
Section: gnome
Maintainer: LiuLang<gsushzhsosgsu@gmail.com>
Architecture: all
Uncompressed Size: 893 k
Depends: gir1.2-gnomekeyring-1.0 | python3-pykde4, gir1.2-gtk-3.0, gir1.2-notify-0.7, gnome-icon-theme-symbolic, libgtk-3-0, libnotify4, notification-daemon, python3-crypto, python3-dbus, python3-gi,
         python3-pyinotify, python3-keyring, python3-lxml
Description: Baidu Pan client for linux users
 Alternative client of Baidu Pan (Baidu Personal Cloud) for linux desktop users.
Homepage: https://github.com/LiuLang/bcloud

网页版登录时会弹出登录成功验证手机的对话框，但可以挂掉，然后成功进入主界面
![screenshot from 2015-08-07 18-37-07-mini](https://cloud.githubusercontent.com/assets/13196353/9134175/64cc5ba2-3d34-11e5-8ed2-0bbcfff5a1aa.png)
有没有可能是这个对话框的原因

**Comment by ghlin** [comment]
如楼上所说 在绑定手机前有这个错误无法登录 绑定手机之后便可以正常登录了 下载也没有问题

**Comment by sunzcdev** [comment]
必须绑定手机号，才能登录

在 2015年8月8日 下午7:23，ghlin <notifications@github.com>写道：

**Comment by jtliaw** [comment]
求救！海外用户无法绑定手机！

**Comment by baoyankun** [comment]
唉，真是流氓透了。

**Comment by secondwtq** [comment]
貌似直接把错误忽略掉就可以了。

**Comment by mhohai** [comment]
https://github.com/LiuLang/bcloud/pull/177    这个已经PR了。
急用的 https://github.com/LiuLang/bcloud/issues/172#issuecomment-136100230

**Comment by LiuLang** [comment]
这个与https://github.com/LiuLang/bcloud/issues/172 是同一个问题. @mhohai 已经提交了补丁.
很抱歉拖了这么久才合并. 版本已经更新到了v3.8.1, 请需要的朋友升级一下吧.
