### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by helinb** [LiuLang/bcloud#172]
有的账号登陆失败，显示未知的错误，请重试，但是，可以登陆网页。

bcloud.log

2015-08-06 19:57:12,351 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 19:58:13,599 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/0b756186fa4ab807a08fa3360ed4902f?fid=1998547108-250528-816960278756920&time=1438858800&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-RRDRCEIaoxTloFtoIQQS4jGOTzU%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100
2015-08-06 19:58:14,049 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/e076ffa3380520f0b236eb182759b4e2?fid=1998547108-250528-156203493117437&time=1438858800&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-au7g%2bzMktGp9BiP%2fBC%2f7PeMm3VU%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100
2015-08-06 19:58:52,168 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 20:01:17,350 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/0b756186fa4ab807a08fa3360ed4902f?fid=1998547108-250528-816960278756920&time=1438862400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-lP0CaJCu1KrtkUcVPAdXb7VMyKw%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100
2015-08-06 20:01:17,804 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/e076ffa3380520f0b236eb182759b4e2?fid=1998547108-250528-156203493117437&time=1438862400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-oh78lv727fX%2flHTxuP47dSWwQAc%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100
2015-08-06 20:03:40,310 ERROR SigninDialog.on_post_login: (4, None), None
2015-08-06 20:03:56,451 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 20:06:37,862 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 20:06:44,159 ERROR SigninDialog.on_post_login: (18, None), None
2015-08-06 20:06:51,981 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/0b756186fa4ab807a08fa3360ed4902f?fid=1998547108-250528-816960278756920&time=1438862400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-lP0CaJCu1KrtkUcVPAdXb7VMyKw%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100
2015-08-06 20:06:52,398 WARNING update_liststore_image(), failed to request http://d.pcs.baidu.com/thumbnail/e076ffa3380520f0b236eb182759b4e2?fid=1998547108-250528-156203493117437&time=1438862400&rt=pr&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-oh78lv727fX%2flHTxuP47dSWwQAc%3d&expires=8h&prisign=unknow&chkbd=0&chkv=0&size=c140_u90&quality=100

**Comment by bsns** [comment]
同样，我的两个帐号都登录失败。

**Comment by solarisbin** [comment]
我只有一个账号，今天发现登陆不了。环境 Ubuntu 14.04
LOG：
2015-08-09 15:16:59,729 ERROR SigninDialog.on_post_login: (18, None), None

**Comment by libreoscar** [comment]
我也遇到了这个问题。好象是baidu多了一个建议绑定手机的步骤，不过网页登录时这个步骤可以忽略。

**Comment by mhohai** [comment]
:+1:  未知错误

**Comment by jtliaw** [comment]
有人说绑定后就能登入了，但我是海外用户另外再开多一个百度户口就没有这个问题了！

**Comment by libreoscar** [comment]
请问“另外再开多一个百度户口”是指？

2015-08-12 20:39 GMT-07:00 jtliaw <notifications@github.com>:

> 有人说绑定后就能登入了，但我是海外用户另外再开多一个百度户口就没有这个问题了！
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LiuLang/bcloud/issues/172#issuecomment-130520490>.
>



-- 
Regards,
Zihan, Sheldon Liu
------------------------------------------------
Software Engineer @ Google Inc.

**Comment by jtliaw** [comment]
就是重新多注册一个百度云盘账户！

**Comment by mhohai** [comment]
大家帐号一齐有风险，看来是百度服务器使用了明文密码，然后别黑客拖库了，所以我们被不安全了 :shell: :laughing:

**Comment by baoyankun** [comment]
不绑定手机，宁可不用。

**Comment by mhohai** [comment]
@baoyankun 反正本来就不怎么用，浏览器下载也可以多线程的。

**Comment by baoyankun** [comment]
@mhohai 浏览器下载超过1G的文件，除了通过wap页面还有别的办法吗？

**Comment by mhohai** [comment]
@baoyankun 我用的火狐浏览器，有个插件downloadthemall。。。

**Comment by m13253** [comment]
> @mhohai 浏览器下载超过1G的文件，除了通过wap页面还有别的办法吗？

如果使用 Linux 的 User-Agent 也可以。

**Comment by mhohai** [comment]
@m13253 我用Linux，本身就是Linux的User-Agent。。。

**Comment by m13253** [comment]
> @m13253 我用Linux，本身就是Linux的User-Agent。。。

我这边 Chrome on Linux 可以下载任意大小的文件。

**Comment by cjxgm** [comment]
绑定后确实可以了……

**Comment by mhohai** [comment]
@cjxgm 我们就是不绑定！！！

**Comment by jtliaw** [comment]
我想绑定都不能绑定！希望大神修改，帮助我等国外朋友！

**Comment by m13253** [comment]
请作者修改代码逻辑，模拟点击“以后绑定”的按钮。

**Comment by baoyankun** [comment]
不能绑定啊，同志们。感谢百度提供这么好的服务。

**Comment by mhohai** [comment]
pull request https://github.com/LiuLang/bcloud/pull/177

**Comment by m13253** [comment]
> pull request 已发，坐等更新。

谢谢贡献！

**Comment by mhohai** [comment]
按捺不住的可以直接改库文件
`$ ls -al /usr/lib/python3/dist-packages/bcloud/auth.py`
增加那两行，注意不要修改文件权限。 (改的话直接vim)

**Comment by m13253** [comment]
@mhohai 话说要不要模拟一下点击按钮的行为？
这样强行绕过会不会有封号危险呢？

**Comment by mhohai** [comment]
@m13253 你自己用浏览器，关掉那个窗口或者刷新试试。。。
已经正常登录成功了，直接忽略这个返回码，我的调试修改已经正常下载文件了。

**Comment by helinb** [comment]
archlinux  改的位置为 /usr/lib/python3.4/site-packages/bcloud/auth.py

**Comment by baoyankun** [comment]
@mhohai 非常感谢！

**Comment by jtliaw** [comment]
请问增加哪两行？
在/usr/lib/python3/dist-packages/bcloud/auth.py的最下方吗？

**Comment by m13253** [comment]
> 在/usr/lib/python3/dist-packages/bcloud/auth.py的最下方吗？

是这个文件，但是不是最下方，
照着这个改 https://github.com/LiuLang/bcloud/pull/177/files

**Comment by jtliaw** [comment]
找到了！非常感谢mhohai，m13253!
在：https://github.com/gshmu/bcloud/blob/master/bcloud/auth.py
复制，粘贴！

**Comment by hepha** [comment]
@mhohai  謝謝你啦！

**Comment by laichiaheng** [comment]
所以現在是要自己手動更改什麼的意思嗎？

**Comment by m13253** [comment]
> 以現在是要自己手動更改什麼的意思嗎？

解决方法已经放出来了。（看上面）
但是要等 LiuLang 本人确认合并到代码库里面。
所以在这之前只有手动改你电脑里面的代码。

**Comment by laichiaheng** [comment]
@m13253 所以是要下載原始碼來編譯囉？

**Comment by m13253** [comment]
> @m13253 所以是要下載原始碼來編譯囉？

因為 bcloud 是用 Python 寫的。所以原始碼就是程式，不需要單獨編譯。
如果你已經安裝了 bcloud 了，那麼 bcloud 的原始碼在：
```
/usr/lib/python3.4/site-packages/bcloud/
```
或者
```
/usr/lib/python3/dist-packages/bcloud/
```
打開它，找到 `auth.py` 把 [這個](https://github.com/gshmu/bcloud/blob/master/bcloud/auth.py) 的內容粘貼進去保存就可以了。
再次啓動 bcloud 就是可以運作了。

**Comment by laichiaheng** [comment]
@m13253 我改了之後 bcloud就打不開了

**Comment by m13253** [comment]
> @m13253 我改了 /usr/lib/python3/dist-packages/bcloud/auth.py 之後 bcloud就打不開了

你可能是哪里改错了。
从终端启动 bcloud-gui 看有输出什么吗？

**Comment by laichiaheng** [comment]
@m13253 
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:1211: unable to lookup signal "window-state-event" of unloaded type 'GtkDialog'
  initialized, argv = Gtk.init_check(sys.argv)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: g_signal_add_emission_hook: assertion 'signal_id > 0' failed
  initialized, argv = Gtk.init_check(sys.argv)

** (bcloud-gui:9844): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-VapDVFEgxY: 連線被拒絕
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3/dist-packages/bcloud/App.py", line 23, in <module>
    from bcloud import gutil
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/usr/lib/python3/dist-packages/bcloud/pcs.py", line 17, in <module>
    from bcloud import auth
  File "/usr/lib/python3/dist-packages/bcloud/auth.py", line 255
    elif err_no == 18:
                     ^
好像就是加的那行出錯了？

**Comment by m13253** [comment]
> 好像就是加的那行出錯了？

列首的空格數目正確嗎？

**Comment by laichiaheng** [comment]
@m13253 什麼意思？

**Comment by laichiaheng** [comment]
我改成您給我的auth.py，則是
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:1211: unable to lookup signal "window-state-event" of unloaded type 'GtkDialog'
  initialized, argv = Gtk.init_check(sys.argv)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: g_signal_add_emission_hook: assertion 'signal_id > 0' failed
  initialized, argv = Gtk.init_check(sys.argv)

** (bcloud-gui:9942): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-VapDVFEgxY: 連線被拒絕
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3/dist-packages/bcloud/App.py", line 23, in <module>
    from bcloud import gutil
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/usr/lib/python3/dist-packages/bcloud/pcs.py", line 17, in <module>
    from bcloud import auth
  File "/usr/lib/python3/dist-packages/bcloud/auth.py", line 4
    <!DOCTYPE html>
    ^

**Comment by laichiaheng** [comment]
@m13253 我改成您給我的auth.py，則是
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: /build/buildd/glib2.0-2.42.2/./gobject/gsignal.c:1211: unable to lookup signal "window-state-event" of unloaded type 'GtkDialog'
  initialized, argv = Gtk.init_check(sys.argv)
/usr/lib/python3/dist-packages/gi/overrides/Gtk.py:1511: Warning: g_signal_add_emission_hook: assertion 'signal_id > 0' failed
  initialized, argv = Gtk.init_check(sys.argv)

** (bcloud-gui:9942): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-VapDVFEgxY: 連線被拒絕
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3/dist-packages/bcloud/App.py", line 23, in <module>
    from bcloud import gutil
  File "/usr/lib/python3/dist-packages/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/usr/lib/python3/dist-packages/bcloud/pcs.py", line 17, in <module>
    from bcloud import auth
  File "/usr/lib/python3/dist-packages/bcloud/auth.py", line 4
    <!DOCTYPE html>
    ^

**Comment by m13253** [comment]
> 我改成您給我的auth.py，則是

你應該打開它複製正文，而不是下載 HTML 文件……

**Comment by laichiaheng** [comment]
@m13253 成功了，但如果是單純加入上面說的 err_no == 18: 的話就出錯，真詭異

**Comment by mhohai** [comment]
我是不是该修改那行`if err_no == 0 or err_no == 18:` 这样就没有这些`诡异`了。 :rocket: 
@laichiaheng python语法没有{}，所以空格tab要求很严格！

**Comment by m13253** [comment]
> 我是不是该修改那行if err_no == 0 or err_no == 18: 这样就没有这些诡异了。 :rocket: 

不必要。你只要静静地等待 @LiuLang merge你的代码即可。

**Comment by mhohai** [comment]
@m13253 上面那句一半是玩笑，万一哪天返回18需要处理了呢，你说是不。。。

**Comment by m13253** [comment]
> @m13253 上面那句一半是玩笑，万一哪天返回18需要处理了呢，你说是不。。。

我想知道 @LiuLang 到底怎么了，已经一个月没有活跃了……急死了。

**Comment by mhohai** [comment]
@m13253 工作忙，表示理解。  经常反复的问题被问三遍，真正的开源是：自己动手，丰衣足食。 :8ball:

**Comment by baoyankun** [comment]
@mhohai 看到你增加的代码我很惭愧！早应该自己动手的。

**Comment by mhohai** [comment]
@baoyankun 为什么惭愧？下次早点动手不就好了 :flags:

**Comment by wxyin** [comment]
@mhohai 关于加入那两行代码后报错的问题，我想我应该找到了一个原因：作者在
```
        if err_no == 0:
            return (0, auth_cookie)
        elif err_no == 18:
            return (0, auth_cookie)
        # 要输入验证码
        elif err_no == 257:
            return (err_no, query)
```
中对齐全部用的空格键（if 和 elif 8次空格, return 12次空格），我出于精简考虑，改成了对应的tab加空格，因此报错，全部改成空格后就OK了

**Comment by m13253** [comment]
> 出于精简考虑，改成了对应的tab加空格，因此报错

Python 自从某个版本之后，如果发现源代码里 Tab 和空格混用，会给出警告，在某些情况下会直接拒绝执行代码。

**Comment by LiuLang** [comment]
楼上的各位朋友:
很抱歉最近三个月一直没更新. 公司项目要发布新版本, 重写了不少东西, 平时要加班到很晚.
好消息是从前天开始, 不再需要加班了.
在这期间, 我手上的几个开源项目, 都暂停了更新, 刚才看了邮箱, 有近两百封邮件没有回复了! 很抱歉没能及时一一回复各位的问题.
这中间出了不少问题, 其中最严重的是两个, bcloud无法正常登录和bcloud下载出错.
现在有时间了, 我会一个个修正这些问题的.

感谢各位朋友的支持.
LiuLang

**Comment by LiuLang** [comment]
已经合并了https://github.com/LiuLang/bcloud/pull/177, 感谢 @mhohai .
紧急制作了v3.8.1, 也打好了deb包, 有需要的朋友可以更新了. https://github.com/LiuLang/bcloud-packages

**Comment by LiuLang** [comment]
@wxyin @m13253  是的, 现在对齐用的是四个空格.

**Comment by libreoscar** [comment]
普天同庆！
2015年9月9日 08:52，"LiuLang" <notifications@github.com>写道：

**Comment by mhohai** [comment]
:100: 应该是感谢你才对 @LiuLang

**Comment by ID4Rasp** [comment]
我曾经提出过在树莓派里无法上传大文件的问题，一直未能解决。刚发现此v3.8.1版本，树莓派除登录还有点小问题（需要在输入框不断按空格键才能进行），上传下载均已基本可正常运行。可能无意中顺便解决了某个BUG，特此报告并感谢各位@LiuLang@mhohai
