### ISSUE TITLE
下载速度特别慢

### ISSUE THREAD

**Issue by ubuntuwbw** [LiuLang/bcloud#173]
我是会员，有200%的下载加速，但下载大文件200-300k，用手机下载5-6M的速度，我看了～/.config/bcould/bcould.log，其中有以下错误：
2015-08-07 09:48:54,248 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/Downloader.py", line 77, in get_req
    return opener.open(self.url, timeout=self.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 493, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 676, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by athrunsun** [comment]
会不会跟[#174](https://github.com/LiuLang/bcloud/issues/174)是一样的原因？
