### ISSUE TITLE
Mac下使用bcloud

### ISSUE THREAD

**Issue by MittWillson** [LiuLang/bcloud#188]
$ bcloud-gui 
Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/site-packages/bcloud/App.py", line 11, in <module>
    from gi.repository import Gdk
ImportError: No module named 'gi'

**Comment by MittWillson** [comment]
找了X11兼容的安装了那些库以后提示报错

2015-10-03 11:07:07.087 Python[48524:589651] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "/Users/Mitt/Downloads/bcloud-master/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/Users/Mitt/Downloads/bcloud-master/bcloud/App.py", line 19, in <module>
    Config.check_first()
  File "/Users/Mitt/Downloads/bcloud-master/bcloud/Config.py", line 74, in check_first
    os.makedirs(CONF_DIR, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by LiuLang** [comment]
On 10/03/2015 11:07 AM, Meng Dejin wrote:
> 找了X11兼容的安装了那些库以后提示报错
>
> 2015-10-03 11:07:07.087 Python[48524:589651] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
> Traceback (most recent call last):
>    File "/Users/Mitt/Downloads/bcloud-master/bcloud-gui", line 11, in <module>
>      from bcloud.App import App
>    File "/Users/Mitt/Downloads/bcloud-master/bcloud/App.py", line 19, in <module>
>      Config.check_first()
>    File "/Users/Mitt/Downloads/bcloud-master/bcloud/Config.py", line 74, in check_first
>      os.makedirs(CONF_DIR, exist_ok=True)
> TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/188#issuecomment-145196893
>

exist_ok 这个参数只在python3的os.makedirs() 函数中存在.
你运行的是python2吧, 嗯, bcloud 需要python3. 如果没有的话, 可以从 
python.org 下载一个tar包, 解开后手动编译一下就有了.

**Comment by MittWillson** [comment]
@LiuLang  貌似mac下没有适合gtk的python库 只有2.7的

Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/site-packages/bcloud/App.py", line 11, in <module>
    from gi.repository import Gdk
  File "/usr/local/lib/python3.5/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/gi/_gi.so, 2): Symbol not found: _PyInt_Type
  Referenced from: /usr/local/lib/python3.5/site-packages/gi/_gi.so
  Expected in: flat namespace
 in /usr/local/lib/python3.5/site-packages/gi/_gi.so

**Comment by MittWillson** [comment]
Traceback (most recent call last):
  File "/Users/Mitt/Downloads/bcloud-master/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/Users/Mitt/Downloads/bcloud-master/bcloud/App.py", line 11, in <module>
    from gi.repository import Gdk
  File "/usr/local/lib/python3.5/site-packages/gi/__init__.py", line 23, in <module>
    from ._gi import _API, Repository
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/gi/_gi.so, 2): Symbol not found: _PyUnicodeUCS2_FromString
  Referenced from: /opt/gtk3/lib/libpyglib-gi-2.0-python3.2.0.dylib
  Expected in: flat namespace
 in /opt/gtk3/lib/libpyglib-gi-2.0-python3.2.0.dylib

**Comment by LiuLang** [comment]
...
我也没辙.
gtk3在windows/mac平台上的支持并不好, 它的C版本目前只更新到了3.6版, 之后的版本就再也没人做迁移了, 据说是人手不够.
算了, 别折腾了 ;-(
百度网盘是有windows和mac的客户端的.

**Comment by MittWillson** [comment]
@LiuLang :-( 要是那个垃圾同步盘好用也不至于我对bcloud这么上心 那同步盘有跟没有一样 看来只能放弃了 谢谢了

**Comment by mhohai** [comment]
买了MAC的，要求用Linux的人去兼容~
你不知道吗，就是因为不兼容，我才写个给自己用……

**Comment by mittwillson** [comment]
@mhohai 因为我们没能力 而且使用的是python的gtk 我也并不抱怨他使用python3来开发 如果是python2.7进行开发的话 无论是mac还是win跑起来都是没问题的 问题就在于gtk3没有mac和linux的python版本 所以才跑不起来 现在我已经配合aria2使用了 此贴已经结了

**Comment by ghost** [comment]
GTK3只适合在Linux使用
要想移植的话，用Qt吧
我已经打算用Qt写了

**Comment by mittwillson** [comment]
@iVanilla 坐等大神的QT成果 如果能解决多个文件下载不用验证码就好了 23333

**Comment by ghost** [comment]
@MittWillson 我不是什么大神，我一个人能力有限，只是希望靠大家的力量去开发出来而已，因为这方面需求还是非常大的。

**Comment by mittwillson** [comment]
@iVanilla 会写的人就是大神
