### ISSUE TITLE
用WiFi不能下载，插上网线速度<700kb/s，我家电信百兆光纤

### ISSUE THREAD

**Issue by SandyBM** [LiuLang/bcloud#189]
首先是感谢作者的贡献！
以前版本也有类似一点下载立马“错误”的情况，由于用火狐就可以下载，所以没在乎。
最近更新到3.8.1版本，经常用WiFi上网。
今晚下载一部3.7GB的电影，才点“下载”，去查看直接“错误”，再点“开始”，还是“错误”。
虽然里无线路由器1米远（不隔墙）还是怀疑网络不稳定，于是插上网线，再点“开始”，立马有速度。
软件首选项的“下载设置”如下：每个下载任务3个连接，重连间隔5分钟，下载超时60秒。
~/.config/bcloud的两个文件已发到您邮箱里了，还望您看看是什么问题。

**Comment by SandyBM** [comment]
忘了说，系统是LinuxMint17(mate)X64

**Comment by LiuLang** [comment]
On 10/05/2015 12:29 AM, SandyBM wrote:
> 首先是感谢作者的贡献！
> 以前版本也有类似一点下载立马“错误”的情况，由于用火狐就可以下载，所以没在乎。
> 最近更新到3.8.1版本，经常用WiFi上网。
> 今晚下载一部3.7GB的电影，才点“下载”，去查看直接“错误”，再点“开始”，还是“错误”。
> 虽然里无线路由器1米远（不隔墙）还是怀疑网络不稳定，于是插上网线，再点“开始”，立马有速度。
> 软件首选项的“下载设置”如下：每个下载任务3个连接，重连间隔5分钟，下载超时60秒。
> ~/.config/bcloud的两个文件已发到您邮箱里了，还望您看看是什么问题。
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/189
>

日志里面记录了特别多的403错误, 下载请求被百度服务器拒绝了.

你先在终端里运行这段代码, 手动删除一下之前的临时授权信息, 再用wifi连接后 
下载, 看是什么情况.

`find ~/.cache/bcloud -type f -iname 'auth.json' |xargs rm`

**Comment by LiuLang** [comment]
On 10/05/2015 12:29 AM, SandyBM wrote:
> 忘了说，系统是LinuxMint17(mate)X64
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/bcloud/issues/189#issuecomment-145364291
>

插上网线后的速度<700k, 因为现在百度有收费会员了, 对普通会员做了限速处理 ;-(

**Comment by qband** [comment]
我也出现了无法下载的情况，log如下，不知道是否是编码问题。我的系统是Arch Linux ARM，bcloud是从archlinuxarm.org的官方仓库里下的。

/usr/lib/python3.5/site-packages/bcloud/SigninDialog.py:65: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  vcode_confirm = Gtk.Button.new_from_stock(Gtk.STOCK_OK)
/usr/lib/python3.5/site-packages/bcloud/SigninDialog.py:65: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  vcode_confirm = Gtk.Button.new_from_stock(Gtk.STOCK_OK)
/usr/lib/python3.5/site-packages/bcloud/HomePage.py:211: Warning: The property GtkAlignment:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  list_view_button.set_image(list_view_img)
/usr/lib/python3.5/site-packages/bcloud/HomePage.py:211: Warning: The property GtkAlignment:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  list_view_button.set_image(list_view_img)
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/bcloud/Downloader.py", line 316, in run
    self.download()
  File "/usr/lib/python3.5/site-packages/bcloud/Downloader.py", line 171, in download
    if os.path.exists(filepath):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 77-78: ordinal not in range(128)

Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/bcloud/Downloader.py", line 316, in run
    self.download()
  File "/usr/lib/python3.5/site-packages/bcloud/Downloader.py", line 171, in download
    if os.path.exists(filepath):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-51: ordinal not in range(128)
