### ISSUE TITLE
似乎无法使用了？

### ISSUE THREAD

**Issue by abcfy2** [LiuLang/bcloud#239]
登录之后显示不出来任何目录列表了。

**Comment by zbli** [comment]
碰到相同问题

**Comment by pingplug** [comment]
同样的问题，估计是百度的锅

**Comment by wangjiezhe** [comment]
点一下左边目录的其它选项就正常了，貌似升级 gnome 3.20 之后就一直这样了。

**Comment by zbli** [comment]
嗯，确实又好了，但是昨晚点击左边目录还没有效果的

**Comment by abcfy2** [comment]
今天确实又好了。

顺便问一下，上传文件(夹)的时候出现多个(1), (2)后缀的文件(夹)是怎么回事？怎么解决？

**Comment by chrdev** [comment]
我的任何目录都是空白，只有 Trash 能显示出来。

bcloud.log 片段

> 2016-06-02 23:38:13,841 ERROR Others.on_load: {'errno': -6, 'request_id': 3571344170132871958}, None
> 2016-06-02 23:38:15,506 ERROR HomePage.on_load: {'errno': -6, 'request_id': 3571344612424424063}, None
> 2016-06-02 23:38:22,264 ERROR HomePage.on_load: {'errno': -6, 'request_id': 3571346430248378833}, None

bcloud-stderr.log

>  Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/bcloud/IconWindow.py", line 644, in on_props_activated
>     dialog = FolderPropertyDialog(self, self.app, self.parent.path)
>   File "/usr/lib/python3.5/site-packages/bcloud/PropertiesDialog.py", line 94, in **init**
>     file_path, file_name = os.path.split(path)
>   File "/usr/lib/python3.5/posixpath.py", line 103, in split
>     i = p.rfind(sep) + 1
> AttributeError: 'gi.FunctionInfo' object has no attribute 'rfind'
