### ISSUE TITLE
登陆显示network error

### ISSUE THREAD

**Issue by sbw983** [LiuLang/bcloud#247]
log：

2016-06-13 23:28:00,327 ERROR HomePage.on_load: {'errno': -6, 'request_id': 3826300469792762869}, None
2016-06-13 23:30:11,814 ERROR Pictures.on_load: {'errno': -6, 'request_id': 3826335866247548698}, None
2016-06-13 23:30:30,022 ERROR HomePage.on_load: {'request_id': 3826340752803475938, 'errno': -6}, None
2016-06-13 23:32:23,199 ERROR Videos.on_load: {'request_id': 3826371138922812605, 'errno': -6}, None
2016-06-13 23:32:24,414 ERROR Documents.on_load: {'request_id': 3826371465656446201, 'errno': -6}, None
2016-06-13 23:32:25,028 ERROR Pictures.on_load: {'request_id': 3826371624852360483, 'errno': -6}, None
2016-06-13 23:32:43,432 ERROR pcs.get_download_link(): {'request_id': 3826376572301803054, 'errno': -6}
2016-06-13 23:32:43,433 WARNING Failed to get url to download
2016-06-13 23:32:47,694 ERROR pcs.get_download_link(): {'request_id': 3826377718292169414, 'errno': -6}
2016-06-13 23:32:47,695 WARNING Failed to get url to download
2016-06-13 23:32:48,128 ERROR pcs.get_download_link(): {'request_id': 3826377834830197889, 'errno': -6}
2016-06-13 23:32:48,129 WARNING Failed to get url to download
2016-06-13 23:32:48,989 ERROR pcs.get_download_link(): {'request_id': 3826378057632289766, 'errno': -6}
2016-06-13 23:32:48,990 WARNING Failed to get url to download
2016-06-13 23:32:49,831 ERROR pcs.get_download_link(): {'request_id': 3826378289868218634, 'errno': -6}
2016-06-13 23:32:49,832 WARNING Failed to get url to download
2016-06-13 23:33:03,114 ERROR HomePage.on_load: {'request_id': 3826381850003518903, 'errno': -6}, None

**Comment by brothermechanic** [comment]
same for me!
Help!

**Comment by licamla** [comment]
this issus is fixed by @poplite on [issuses#244](https://github.com/LiuLang/bcloud/issues/244)

**Comment by brothermechanic** [comment]
Why you don't update git master?

**Comment by licamla** [comment]
I am not the administrator of this git, and there are other issuse on download sometime.

**Comment by yan12125** [comment]
Get the same issue. From Wireshark I see `/api/list` calls but there are no responses.

By the way, bypy works fine.

**Comment by xsitian** [comment]
I get the same error, please fix,many thanks!

**Comment by RanchoCooper** [comment]
where is the bcloud.log file located?

**Comment by yan12125** [comment]
> where is the bcloud.log file located?

On Linux, `~/.config/bcloud`

**Comment by yan12125** [comment]
I've pushed @poplite's patch to #248.

**Comment by RanchoCooper** [comment]
分别修改了auth.py和pcs.py但还是有错

bcloud.log:

```
2016-06-30 10:41:47,113 ERROR HomePage.on_load: {'request_id': 4208237699434896688, 'errno': -6}, None
2016-06-30 10:41:55,418 ERROR 图片.on_load: {'request_id': 4208239945972000905, 'errno': -6}, None
2016-06-30 10:41:56,739 ERROR 文档.on_load: {'request_id': 4208240301112036652, 'errno': -6}, None
2016-06-30 10:42:46,904 ERROR HomePage.on_load: {'request_id': 4208253756094206522, 'errno': -6}, None
2016-06-30 10:42:52,375 ERROR 音乐.on_load: {'request_id': 4208255234394021862, 'errno': -6}, None
2016-06-30 10:42:53,083 ERROR BT.on_load: {'request_id': 4208255424252202525, 'errno': -6}, None
2016-06-30 10:42:53,355 ERROR 视频.on_load: {'request_id': 4208255499386501386, 'errno': -6}, None
2016-06-30 10:43:44,838 ERROR 图片.on_load: {'request_id': 4208269307755814564, 'errno': -6}, None
2016-06-30 10:43:45,955 ERROR 文档.on_load: {'request_id': 4208269620351163949, 'errno': -6}, None
2016-06-30 10:43:50,392 ERROR HomePage.on_load: {'request_id': 4208270807722526046, 'errno': -6}, None
2016-06-30 10:43:51,076 ERROR HomePage.on_load: {'request_id': 4208270993128607818, 'errno': -6}, None
2016-06-30 10:43:53,802 ERROR HomePage.on_load: {'request_id': 4208271723606703069, 'errno': -6}, None
2016-06-30 10:43:54,726 ERROR HomePage.on_load: {'request_id': 4208271972689504113, 'errno': -6}, None
2016-06-30 12:18:29,244 ERROR HomePage.on_load: {'errno': -6, 'request_id': 4209795162190047906}, None
2016-06-30 12:21:27,384 ERROR BT.on_load: {'errno': -6, 'request_id': 4209842979975846386}, None
2016-06-30 12:21:27,723 ERROR 视频.on_load: {'errno': -6, 'request_id': 4209843085680904827}, None
2016-06-30 12:21:28,520 ERROR 文档.on_load: {'errno': -6, 'request_id': 4209843301053170454}, None
2016-06-30 12:21:28,572 ERROR 图片.on_load: {'errno': -6, 'request_id': 4209843313353075823}, None

```

**Comment by yan12125** [comment]
這邊有一些其他解法：https://github.com/LiuLang/bcloud/network

**Comment by yufeikang** [comment]
这个问题我改了 https://github.com/Yufeikang/bcloud

**Comment by sbw983** [comment]
@Yufeikang 用来你修改的版本还是不能登陆，出错信息如下
./bcloud-gui 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    external_cssselect = **import**('cssselect')
ImportError: No module named 'cssselect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/App.py", line 27, in <module>
    from bcloud import gutil
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/pcs.py", line 15, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 18, in <module>
    raise ImportError('cssselect seems not to be installed. '
ImportError: cssselect seems not to be installed. See http://packages.python.org/cssselect/

python-cssselect v 0.9.1已安装
我的系统是ubuntu 14.04 x64

**Comment by xanpeng** [comment]
@sbw983

**Comment by xanpeng** [comment]
@sbw983 
sudo -i
sudo apt-get install python3-pip
pip3 install cssselect

**Comment by sbw983** [comment]
@xanpeng 多谢，搞定
