### ISSUE TITLE
下载挂起，不能继续的问题

### ISSUE THREAD

**Issue by ubuntuwbw** [LiuLang/bcloud#249]
还是有下载挂起，不能继续的问题，需要停止再启动才可以，日志中有如下问题：
2016-08-14 18:21:15,065 ERROR Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/bcloud/net.py", line 66, in urlopen_simple
    return urllib.request.urlopen(url, timeout=timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1257, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

**Comment by poplite** [comment]
试一下换用PC端的User-agent下载看看.

**Comment by mozbugbox** [comment]
你这个在 git head 里已经解决了: commit 3a2cb54f53c7a808c204efb3c848710edfcb2865
