### ISSUE TITLE
启动bcloud出错

### ISSUE THREAD

**Issue by sbw983** [LiuLang/bcloud#260]
使用的是20160923的版本

系统ubuntu 14.04 x64
cssselect v0.9.1已安装

出错信息：
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    external_cssselect = **import**('cssselect')
ImportError: No module named 'cssselect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/App.py", line 27, in <module>
    from bcloud import gutil
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/home/sbw983/Tools/Baidu/bcloud-master/bcloud/pcs.py", line 15, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 18, in <module>
    raise ImportError('cssselect seems not to be installed. '
ImportError: cssselect seems not to be installed. See http://packages.python.org/cssselect/

**Comment by zhenguoli** [comment]
需要安装python3对应的cssselect, 执行`sudo apt-get install python3-cssselect`.

**Comment by viewtheard** [comment]
现在变成这个了。请问算是装完了吗?
root@DebianPC:/tmp# bcloud-gui
Gkr-Message: couldn't connect to dbus session bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Please set a password for your new keyring:

**Comment by sbw983** [comment]
bcloud已经连不上百度云，建议用BaiduPCS吧，只不过没有gui而已，但是胜在稳定
项目地址：
https://github.com/GangZhuo/BaiduPCS

**Comment by viewtheard** [comment]
PCS那边换了新api,限速了，下载一个就要重新登录一次。百毒漏洞越来越少l
