### ISSUE TITLE
setup安装后，运行不了

### ISSUE THREAD

**Issue by zzugyl** [LiuLang/bcloud#277]
通过setup安装后，运行不起来
`~$ bcloud-gui 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 13, in <module>
    import cssselect as external_cssselect
ImportError: No module named 'cssselect'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/dist-packages/bcloud/App.py", line 30, in <module>
    from bcloud import gutil
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 20, in <module>
    from bcloud import pcs
  File "/usr/local/lib/python3.5/dist-packages/bcloud/pcs.py", line 14, in <module>
    from lxml.cssselect import CSSSelector as CSS
  File "/usr/lib/python3/dist-packages/lxml/cssselect.py", line 16, in <module>
    'cssselect does not seem to be installed. '
ImportError: cssselect does not seem to be installed. See http://packages.python.org/cssselect/`
但是安装了cssselect。
`~$ pip install cssselect
Requirement already satisfied: cssselect in ./.local/lib/python2.7/site-packages`
通过ppa源可以安装运行。

**Comment by owenxu10** [comment]
用pip3装
