### ISSUE TITLE
bcloud-gui运行不了

### ISSUE THREAD

**Issue by viewtheard** [LiuLang/bcloud#279]
# bcloud-gui

Traceback (most recent call last):
  File "/usr/local/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/local/lib/python3.5/dist-packages/bcloud/App.py", line 27, in <module>
    from bcloud import gutil
  File "/usr/local/lib/python3.5/dist-packages/bcloud/gutil.py", line 21, in <module>
    from bcloud import pcs
  File "/usr/local/lib/python3.5/dist-packages/bcloud/pcs.py", line 14, in <module>
    from lxml import html
ImportError: No module named 'lxml'

=================
apt-get install libxml2-dev libxslt-dev
apt-get install python-lxml
都用过了。
ps:debian 9 运行不了，求助。

**Comment by poplite** [comment]
装python3版本的库。

**Comment by viewtheard** [comment]
# sudo apt-get install python3-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
python3-dev 已经是最新版 (3.5.3-1)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 5 个软件包未被升级。

装过了啊，求教详细步骤，我是新手

**Comment by poplite** [comment]
`sudo apt-get install python3-lxml`，如此类推。
提醒一下，Liulang的bcloud已经无法使用了(新版本缓慢重写中)，别人fork改写的还可以使用。

**Comment by wangbaiwan** [comment]
pip3 install lxml
